name: Build & Release Filesystem

on:
    # push:
    #   branches:
    #     - main
    #   paths:
    #     - data/**
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        run: pio run --target buildfs --environment ESP32
      - name: Copy file system *.bin file
        run: cp .pio/build/ESP32/littlefs.bin filesystem.bin
      - name: Generate checksum
        run: |
          echo CHECKSUM="$(sha256sum filesystem.bin | awk '{ print $1 }')" >> "$GITHUB_ENV"  
      - name: Write checksum to release checksum file
        run: |
          echo $CHECKSUM > filesystem.bin.sha256
      - name: Get current date for release tag
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Upload release to Github
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Filesystem Release ${{ env.NOW }}
          tag_name: filesystem
          body: |
            - SHA256: ${{ env.CHECKSUM }}
          draft: true
          files: |
            filesystem.bin
            filesystem.bin.sha256